version: '3'
services:
  asap-demo:
    #context: .
    #build: .
    image: waelrash1/r-shiny-studio-forecasting #asap-img
    container_name: wael
    restart: always
    ports:
      - "1160:8787"
      - "1170:3838"
    environment:
     - ROOT= TRUE
     - PASSWORD= "ontheway" 
    volumes:
      - /wd/rwd:/home/rstudio
      - /wd/rwd/shiny-apps:/srv/shiny-server
      - /wd/rwd/shiny-logs/:/var/log/shiny-server 
    expose:
      - 8787
      - 3838